#!/usr/bin/env bash

# tools to install
askWhichTool() {
    echo "What do you want to install?
zsh
nvm
docker
code-server
"

    local tool=""
    read -e -rp "Type ahead with your choice: " tool
    installTool $tool
}

installTool() {
    local tool=$1
    echo "Installing $tool"
    if [[ $tool == "development-kit" ]]; then
        "install.sh" | bash
    else
        curl -o- "https://raw.githubusercontent.com/FirzenYogesh/development-kit/main/$tool-kit.sh" | bash
    fi
}

uninstallTool() {
    local tool=$1
    echo "Uninstalling $tool"
    if [[ $tool == "development-kit" ]]; then
        rm -rf $HOME/.development-tools
    else
        curl -o- "https://raw.githubusercontent.com/FirzenYogesh/development-kit/main/$tool-kit.sh" | bash -s uninstall
    fi
}

if [[ $1 == "install" ]]; then
    installTool $2
elif [[ $1 == "uninstall" ]] || [[ $1 == "remove" ]] || [[ $1 == "purge" ]]; then
    uninstallTool $2
fi