name: Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: shellcheck
      uses: ludeeus/action-shellcheck@0.5.0
      env:
        SHELLCHECK_OPTS: -e SC1091
